name: ceportal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  device_preview: ^1.1.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: "^0.13.1"
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  table_calendar: ^3.0.9
  file_picker: ^6.2.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/fonts/
    - lib/assets/images/categories/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#flutter pub get
#flutter pub run flutter_launcher_icons